'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5420
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("sn0wbreeze.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property adsfdsfsd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adsfdsfsd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Arrow1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arrow1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Arrowgray() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arrowgray", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Arrowhilite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arrowhilite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrowpress() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrowpress", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property attena() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("attena", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property atv2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("atv2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property back_over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back_over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property back_press() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back_press", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property back1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property back2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backg1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backg1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backg11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backg11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backg2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backg2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Backing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Backing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property basebandmode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("basebandmode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blankbacking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blankbacking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BootLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BootLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BootLogosHighLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BootLogosHighLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BootLogosHighLight1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BootLogosHighLight1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BootLogosNorm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BootLogosNorm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BootLogosNorm1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BootLogosNorm1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BuildHighlight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BuildHighlight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BuildNorm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BuildNorm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cancel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cancel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CancelClicked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CancelClicked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property connectatv2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("connectatv2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CustomPKGHighLight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CustomPKGHighLight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CustomPKGHighLight1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CustomPKGHighLight1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CustomPKGNorm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CustomPKGNorm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CustomPKGNorm1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CustomPKGNorm1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cydia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cydia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuConnect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuConnect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuOneButton01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuOneButton01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuOneButton02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuOneButton02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuOneButton03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuOneButton03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuOneButton04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuOneButton04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuOneButton05() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuOneButton05", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuOneButton06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuOneButton06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuOneButton07() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuOneButton07", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuOneButton08() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuOneButton08", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuOneButton09() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuOneButton09", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuOneButton10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuOneButton10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuPrepare() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuPrepare", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuPrepare01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuPrepare01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuPrepare02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuPrepare02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuPrepare03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuPrepare03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuPrepare04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuPrepare04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuPrepare05() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuPrepare05", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuPressTwoButtons() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuPressTwoButtons", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuRelease() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuRelease", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuSuccess() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuSuccess", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuTurnOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuTurnOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuTwoButtons01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuTwoButtons01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuTwoButtons02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuTwoButtons02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuTwoButtons03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuTwoButtons03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuTwoButtons04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuTwoButtons04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuTwoButtons05() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuTwoButtons05", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuTwoButtons06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuTwoButtons06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuTwoButtons07() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuTwoButtons07", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuTwoButtons08() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuTwoButtons08", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuTwoButtons09() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuTwoButtons09", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfuTwoButtons10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuTwoButtons10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfutwobuttons11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfutwobuttons11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfutwobuttons12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfutwobuttons12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfutwobuttons13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfutwobuttons13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfutwobuttons14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfutwobuttons14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfutwobuttons15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfutwobuttons15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfutwobuttons16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfutwobuttons16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfutwobuttons17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfutwobuttons17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfutwobuttons18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfutwobuttons18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfutwobuttons19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfutwobuttons19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfutwobuttons20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfutwobuttons20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfutwobuttons21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfutwobuttons21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfutwobuttons22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfutwobuttons22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfutwobuttons23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfutwobuttons23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfutwobuttons24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfutwobuttons24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfutwobuttons25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfutwobuttons25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfutwobuttons26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfutwobuttons26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfutwobuttons27() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfutwobuttons27", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfutwobuttons28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfutwobuttons28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfutwobuttons29() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfutwobuttons29", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfutwobuttons30() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfutwobuttons30", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property expertm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("expertm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Flake() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Flake", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Flakeselect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Flakeselect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GeneralHighlight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GeneralHighlight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GeneralHighlight1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GeneralHighlight1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GeneralNorm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GeneralNorm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GeneralNorm1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GeneralNorm1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property go_next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("go_next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GPL_button_black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GPL_button_black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GPL_button_over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GPL_button_over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property i4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("i4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property InstallerHighlight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InstallerHighlight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property InstallerHighlight1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InstallerHighlight1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property InstallerNorm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InstallerNorm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property InstallerNorm1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InstallerNorm1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ipad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ipad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iPhone3GS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iPhone3GS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ipt3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ipt3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ipt4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ipt4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mainbord() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mainbord", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mainbord1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mainbord1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property next_over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next_over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property next_over1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next_over1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property next_press() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next_press", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property next_press1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next_press1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property next1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property next2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NextBtn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NextBtn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pacman() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("pacman", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property rawr() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("rawr", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property RecoveryLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RecoveryLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property redhover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redhover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reflectionImage2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reflectionImage2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property remote_both() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("remote_both", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property remote_self() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("remote_self", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property runningireb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("runningireb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property simplem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("simplem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sn0wflak3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sn0wflak3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property spinny() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("spinny", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property start_button_black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("start_button_black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property start_button_over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("start_button_over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property turn_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("turn_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property unicorn_rainbow1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("unicorn_rainbow1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property UNLOCKHighLight1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UNLOCKHighLight1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property UNLOCKNorm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UNLOCKNorm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property UNLOCKNorm1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UNLOCKNorm1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property X() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("X", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
